### ISSUE TITLE
Allow proxy settings to be passed in via Vagrantfile

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/JJG-Ansible-Windows#1]
When I'm using this with Vagrant in a shared environment (where some devs are on Windows, some on Mac), it's annoying to have to remember to edit the windows.sh file on some of the machines when behind a proxy, so I'd like to make it so the proxy setting (either whether to use it or not, or the proxy details themselves) can be set via an argument in the shell provisioner.

I should be able to simply use `args` in the Vagrantfile to pass in an argument (see: http://docs.vagrantup.com/v2/provisioning/shell.html), so this shouldn't be too difficult.

**Comment by geerlingguy** [comment]
I haven't really had the need for this outside of one small use case (for a previous employer), and nobody else has asked for it, so I'm going to close this issue.

**Comment by hordijk** [comment]
See http://tmatilai.github.io/vagrant-proxyconf/ which could be used to set proxy settings using the vagrant file instead.

**Comment by geerlingguy** [comment]
That sounds helpful—better to configure it on the machine level rather than inside this one script!
