### ISSUE TITLE
Move ez_setup.py into repository for security

### ISSUE THREAD

**Issue by cmwelsh** [geerlingguy/JJG-Ansible-Windows#11]
This script currently pulls down the file `ez_setup.py` from:

http://peak.telecommunity.com/dist/ez_setup.py

This link is not available over SSL. It would be more secure to host it here and download it over HTTPS from GitHub.

**Comment by geerlingguy** [comment]
Would the copy available here work correctly?

https://raw.githubusercontent.com/ActiveState/ez_setup/master/ez_setup.py

That's the version linked from the Python package index, and it's available via HTTPS.

**Comment by cmwelsh** [comment]
Yeah that would work. You can even curl a specific release. Seems to work for [nvm](https://github.com/creationix/nvm#install-script).

https://raw.githubusercontent.com/ActiveState/ez_setup/v0.9/ez_setup.py

**Comment by geerlingguy** [comment]
Works for me, thanks for opening this issue!
