### ISSUE TITLE
Problem executing windows.sh (unable to locate playbook.yml)

### ISSUE THREAD

**Issue by jcornide** [geerlingguy/JJG-Ansible-Windows#18]
Hi,
I don't know if this is the proper channel for this, sorry if not.

I'm trying to make my Vagrant (which uses ansible) compatible with windows and I found your script which seems great, but I found a problem.
I set up the Vagrantfile more or less as you specified in your instruction (see below) but when I execute vagrant provision I get this error: Cannot find Ansible playbook.
I added this to the windows.sh to be able to know what file is it looking for:
```
# Make sure Ansible playbook exists.
if [ ! -f "$ANSIBLE_PLAYBOOK" ]; then
  echo "Cannot find Ansible playbook $ANSIBLE_PLAYBOOK"
  exit 1
fi
```
and what I get is ansible/playbook.yml which is correct.

My directory structure is as follow:
Vagrantfile
- /ansible/
  - playbook.yml
  - windows.sh
  - ...

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


require 'rbconfig'
is_windows = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/)



Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"	

  config.vm.network "forwarded_port", guest: 80, host: 8088
  config.vm.network "private_network", ip: "192.168.56.100"

  config.vm.hostname = "development"

  config.vm.synced_folder ".", "/var/www/socialcar.dev"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end	
  
  if is_windows
  # Provisioning configuration for shell script.
    config.vm.provision "shell" do |sh|
      sh.path = "ansible/windows.sh"
      sh.args = "ansible/playbook.yml"
    end
  else
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.verbose = 'vvv'
      ansible.inventory_path = "ansible/hosts"
      ansible.limit = 'all'
    end
  end
end
```

**Comment by geerlingguy** [comment]
Can you try `/ansible/playbook.yml`?

See, for example: https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L55

This might be a documentation issue.

**Comment by pyro2927** [comment]
@jcornide: after you spin up your VM, is the playbook available at `/vagrant/ansible/playbook.yml`.  I had some issues with mounting `/vagrant`, and after working around those the script worked.

**Comment by geerlingguy** [comment]
That would do it too. The `/vagrant` mount has to be working correctly for `windows.sh` to do anything right.

**Comment by jcornide** [comment]
Hi,
Yes! it works now! i suggest you to add this to the vagrantfile documentation example to avoid confusions:
```
config.vm.synced_folder ".", "/vagrant"
```

**Comment by pyro2927** [comment]
I think by default vagrant is supposed to sync that folder. Maybe they changed that in a recent version?

**Comment by geerlingguy** [comment]
Typically that _is_ set up by default... it could be that whatever Vagrantfile you had was disabling that share for some reason, and adding it back in manually resolved the issue.
