### ISSUE TITLE
pip installation method

### ISSUE THREAD

**Issue by DmitryRomanenko** [geerlingguy/JJG-Ansible-Windows#24]
Please check these changes:

    echo "Installing pip via easy_install."
    wget https://raw.githubusercontent.com/ActiveState/ez_setup/v0.9/ez_setup.py
    python ez_setup.py && rm -f ez_setup.py
    easy_install pip

    # Make sure setuptools are installed crrectly.
    pip install setuptools --no-use-wheel --upgrade

Change to:

    echo "Installing pip."
    wget https://bootstrap.pypa.io/get-pip.py
    python get-pip.py && rm -f get-pip.py

It will fix Ubuntu errors (14.04, 15.10), but I haven't tested it on other Linux distributions.

We still need this fix because ansible_local is broken for Windows hosts.

**Comment by geerlingguy** [comment]
Testing this now.

**Comment by geerlingguy** [comment]
Looks like it works okay; going to commit the fix.

**Comment by geerlingguy** [comment]
In tag 1.2.0.
