### ISSUE TITLE
Passing extra-vars on sh.args

### ISSUE THREAD

**Issue by joao-fidalgo** [geerlingguy/JJG-Ansible-Windows#25]
Is it possible to pass ansible variables to the playbook using JJG-Ansible-Windows?

**Comment by oxyc** [comment]
Yes, you there's an `-e` flag (also `--extra-vars`) you can use:

```sh
windows.sh -e 'foo=bar' provisioning/playbook.yml
```

**Comment by joao-fidalgo** [comment]
I'm guessing vagrant shell provisioner doesn't like the extra-vars flag.

**Comment by oxyc** [comment]
I'm using it in [this PR](https://github.com/geerlingguy/drupal-vm/pull/378/files) over at Drupal VM and I'm pretty sure I tested it (from osx host).

**Comment by joao-fidalgo** [comment]
I got it working, thanks a lot!

**Comment by oxyc** [comment]
Glad you got it working!

**Comment by geerlingguy** [comment]
@oxyc++
