### ISSUE TITLE
Pip installation does not work on Ubuntu 16.04

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/JJG-Ansible-Windows#29]
I tried running the script on Ubuntu 16.04 but it fails when using the `pip` command. I noticed I had an outdated base box so updating it to see if anything changes.

```
==> drupalvm: Installing required python modules.
==> drupalvm: Traceback (most recent call last):
==> drupalvm:   File "/usr/local/bin/pip", line 5, in <module>
==> drupalvm:     from pkg_resources import load_entry_point
==> drupalvm: ImportError: No module named pkg_resources
==> drupalvm: Installing Ansible.
==> drupalvm: Traceback (most recent call last):
==> drupalvm:   File "/usr/local/bin/pip", line 5, in <module>
==> drupalvm:
==> drupalvm: from pkg_resources import load_entry_point
==> drupalvm: ImportError
==> drupalvm: :
==> drupalvm: No module named pkg_resources
```

**Comment by oxyc** [comment]
Looking at how your 16.04 box differs from 14.04 I wonder if this has something to do with it https://github.com/geerlingguy/packer-ubuntu-1604/blob/6ff79480c88d60c925e4673b2b0fdef379fc245c/scripts/cleanup.sh#L17:L19.

I've never used packer though.

**Comment by oxyc** [comment]
On docker everything works with stock ansible (`2.0.0.2-2`) btw.

**Comment by oxyc** [comment]
Seems the latest version of the box did solve it!

**Comment by geerlingguy** [comment]
Woohoo, things I don't have to fix!
